*******************************************************************************
* yaml_write
*! v 2.0.1   06Aug2026               by Joao Pedro Azevedo (UNICEF)
* Write Stata data to YAML file
* v 2.0.1: scalars() writes quote-bearing string scalars safely (compound
*   quotes on the scalar line; plain quotes aborted r(198) mid-file).
* v 2.0.0: (1) emit sequences of mappings: a type=="list_map" row prints as a
*   dash item, with its first child folded onto the dash line and remaining
*   children indented beneath it, so map lists round-trip to dash form;
*   (2) literal fidelity: boolean rows are written as true/false (not 1/0)
*   and null rows as an empty value, so a read-write cycle preserves YAML
*   literals rather than Stata's normalized storage values;
*   (3) deterministic output: the header no longer includes a wall-clock
*   "# Date:" line by default, so a written file reproduces byte-for-byte
*   across runs. The new timestamp option restores the date line, and
*   noheader suppresses the header comment entirely.
*******************************************************************************

program define yaml_write
    version 14.0

    syntax using/ [, Scalars(string) FRAME(string) Replace Verbose INDENT(integer 2) HEADER(string) TImestamp NOHEADer]

    * If frame specified, add yaml_ prefix if not present
    if ("`frame'" != "") {
        if (`c(stata_version)' < 16) {
            di as err "frame() option requires Stata 16 or later"
            exit 198
        }
        if (substr("`frame'", 1, 5) != "yaml_") {
            local frame "yaml_`frame'"
        }
    }

    * Check if file exists and handle replace
    capture confirm file "`using'"
    if (_rc == 0 & "`replace'" == "") {
        di as err "file `using' already exists. Use 'replace' option."
        exit 602
    }

    * Open file for writing. quietly: -write replace- notes "(file ... not
    * found)" when the file does not exist yet, which is not worth reporting.
    tempname fh
    quietly file open `fh' using "`using'", write text replace

    * Write header comment. Output is deterministic by default (no wall-clock
    * timestamp), so a written file reproduces byte-for-byte across runs; the
    * timestamp option opts back into a "# Date:" line, and noheader suppresses
    * the header comment entirely.
    if ("`noheader'" == "") {
        if ("`header'" != "") {
            file write `fh' "# `header'" _n
        }
        else {
            file write `fh' "# Generated by Stata yaml write" _n
        }
        if ("`timestamp'" != "") {
            file write `fh' "# Date: `c(current_date)' `c(current_time)'" _n
        }
    }

    * If scalars option, write scalars
    if ("`scalars'" != "") {
        foreach s of local scalars {
            * Confirm the scalar exists. "capture scalar `s'" is NOT a validity
            * test (bare "scalar name" is not a command; it returns rc 100 even
            * when the scalar is defined), which silently skipped every scalar.
            capture confirm scalar `s'
            if (_rc == 0) {
                * plain expression assignment so string scalars work too
                local val = `s'
                * Compound quotes: a string scalar whose value contains a
                * double quote would otherwise terminate the string early,
                * aborting r(198) and leaving a truncated file behind. The
                * main write path below already uses this form.
                file write `fh' `"`s': `val'"' _n
            }
        }
    }
    else {
        * Write from dataset or frame
        if ("`frame'" != "") {
            * Ensure frame exists
            capture frame `frame': describe
            if (_rc != 0) {
                di as err "frame `frame' not found"
                exit 198
            }
            frame `frame' {
                _yaml_write_impl `fh', indent(`indent')
            }
        }
        else {
            _yaml_write_impl `fh', indent(`indent')
        }
    }

    file close `fh'

    if ("`verbose'" != "") {
        di as text "YAML written to `using'"
    }
end

program define _yaml_write_impl
    syntax anything(name=fh) [, INDENT(integer 2)]

    * Ensure required variables exist
    capture confirm variable key value level type
    if (_rc != 0) {
        di as err "Data must include key, value, level, type variables. Use yaml read first."
        exit 198
    }

    * Check for parent variable (needed for leaf key extraction)
    capture confirm variable parent
    local has_parent = (_rc == 0)

    * Pending sequence-of-mappings item: when a list_map row is seen, the
    * dash is held back so the item's FIRST child can be folded onto it
    * ("- from: 1"); remaining children print at their own indentation.
    local dash_pending = 0
    local dash_key ""
    local dash_spaces ""

    * Write rows in observation order (do NOT sort -- insertion order = file order)
    local n = _N
    forvalues i = 1/`n' {
        local k = key[`i']
        local v = value[`i']
        local l = level[`i']
        local t = type[`i']
        local p = ""
        if (`has_parent') {
            local p = parent[`i']
        }

        * Build indentation: (level - 1) * indent spaces
        local nspaces = (`l' - 1) * `indent'
        local spaces ""
        forvalues j = 1/`nspaces' {
            local spaces "`spaces' "
        }

        * Extract leaf key name by stripping parent prefix
        local leaf "`k'"
        if (`has_parent' & "`p'" != "") {
            local plen = length("`p'")
            if (substr("`k'", 1, `plen') == "`p'" & substr("`k'", `plen' + 1, 1) == "_") {
                local leaf = substr("`k'", `plen' + 2, .)
            }
        }

        * Literal fidelity: booleans back to true/false, null to empty
        if ("`t'" == "boolean") {
            if ("`v'" == "1") local v "true"
            else if ("`v'" == "0") local v "false"
        }
        else if ("`t'" == "null") {
            local v ""
        }

        * Flush a pending dash whose item turned out to have no children
        if (`dash_pending' & "`p'" != "`dash_key'") {
            file write `fh' "`dash_spaces'-" _n
            local dash_pending = 0
        }

        if ("`t'" == "list_map") {
            local dash_pending = 1
            local dash_key "`k'"
            local dash_spaces "`spaces'"
        }
        else if (`dash_pending' & "`p'" == "`dash_key'") {
            * First child of the pending item: fold onto the dash line
            file write `fh' `"`dash_spaces'- `leaf': `v'"' _n
            local dash_pending = 0
        }
        else if ("`t'" == "parent") {
            file write `fh' "`spaces'`leaf':" _n
        }
        else if ("`t'" == "list_item") {
            file write `fh' `"`spaces'- `v'"' _n
        }
        else if ("`t'" == "null") {
            file write `fh' "`spaces'`leaf':" _n
        }
        else {
            file write `fh' `"`spaces'`leaf': `v'"' _n
        }
    }

    * Trailing childless dash item
    if (`dash_pending') {
        file write `fh' "`dash_spaces'-" _n
    }
end
